# ==========================================
# Windows Folder Pre-Validation
# ==========================================

source.folder=C:/ESUN-DATAMIGRATION/CB/Data Transition test sample cases 17082026

validation.location=D:/Test Folder/CB-PROCESSED/Migration Validation

cb.error.excel=D:/Test Folder/CB-PROCESSED/Migration_Error_Data.xlsx

pb.error.excel=D:/Test Folder/PB-PROCESSED/Migration_Error_Data.xlsx