# ==========================================
# CB Excel Pre-Validation
# ==========================================

cb.input.excel.path=C:/ESUN-DATAMIGRATION/CB/CB Data transition logic1_ 18082026.xlsx
cb.migration.excel.path=D:/Test Folder/CB-PROCESSED/Migration_Data.xlsx
cb.error.excel.path=D:/Test Folder/CB-PROCESSED/Migration_Error_Data.xlsx


# ==========================================
# PB Excel Pre-Validation
# ==========================================

pb.input.excel.path=C:/ESUN-DATAMIGRATION/PB/New data transition logic_PB_20082026.xlsx
pb.migration.excel.path=D:/Test Folder/PB-PROCESSED/Migration_Data.xlsx
pb.error.excel.path=D:/Test Folder/PB-PROCESSED/Migration_Error_Data.xlsx